server:
  port: 8081
spring:
  datasource:
    username: ITDBA
    password: dyAdfgYuk21332
    url: jdbc:mysql://47.93.98.147:2206/jt-pos-prod?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: /view/
#      suffix: .ftl
#  freemarker:
#    template-loader-path: classpath:/template/, classpath:/template/*
#    check-template-location: true
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    #content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.thinkingingis.domain
logging:
  level:
    com:
      example:
        material:
          Dao: DEBUG
#war:
#  context-path: /qrcode
#spring:
#  # 同一tomcat下多个SpringBoot
#  jmx:
#    enabled: false
#  mvc:
#    static-path-pattern: /static/**
#templates:
#  prefix: /template/
#  freemarker:
#    template-loader-path: classpath:/templates/, classpath:/templates/*
#      cache: false
#logging:
#  level:
#    com:
#      example:
#        mapper : debug
# 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
#  spring.freemarker.allow-request-override=false
#  # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
#  spring.freemarker.allow-session-override=false
#  # 是否启用模板缓存。
#  spring.freemarker.cache=false
#  # 模板编码。
#  spring.freemarker.charset=UTF-8
#  # 是否检查模板位置是否存在。
#  spring.freemarker.check-template-location=true
#  # Content-Type value.
#  spring.freemarker.content-type=text/html
#  # 是否启用freemarker
#  spring.freemarker.enabled=true
#  # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
#  spring.freemarker.expose-request-attributes=false
#  # 是否在merge模板的时候，将HttpSession属性都添加到model中
#  spring.freemarker.expose-session-attributes=false
#  # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
#  spring.freemarker.expose-spring-macro-helpers=true
#  # 是否优先从文件系统加载template，以支持热加载，默认为true
#  spring.freemarker.prefer-file-system-access=true
#  # 设定模板的后缀.
#  spring.freemarker.suffix=.ftl
#  # 设定模板的加载路径，多个以逗号分隔，默认:
#  spring.freemarker.template-loader-path=classpath:/templates/
#  # 设定FreeMarker keys.
#  spring.freemarker.settings.template_update_delay=0
#  spring.freemarker.settings.default_encoding=UTF-8
#  spring.freemarker.settings.classic_compatible=true

